configurationDefinitions:
  - platform: KUBERNETESCLUSTER
    type: AgentConfig
    version: 1.0.0
    format: yml
    bindings:
      - type: CONFIGURES
        targetType: AGENT
        target: PipelineControlGatewayConfigMode
        versions:
          - ">=2.4.2"
