apiVersion: v2
name: mssql-otel
description: A Helm chart to monitor Microsoft SQL Server with New Relic's OpenTelemetry distribution (NRDOT)
type: application
version: 0.1.0
appVersion: "2.4.0"
home: https://github.com/newrelic/helm-charts
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
dependencies:
  - name: common-library
    version: 2.3.3
    repository: "https://helm-charts.newrelic.com"
keywords:
  - mssql
  - sqlserver
  - opentelemetry
  - newrelic
  - monitoring
  - database
maintainers:
  - name: newrelic
    url: https://github.com/newrelic/helm-charts
