# Chart to Label mapping for actions/labeler
agent-control-bootstrap:
  - changed-files:
      - any-glob-to-any-file: 'charts/agent-control-bootstrap/*'
agent-control-cd:
  - changed-files:
      - any-glob-to-any-file: 'charts/agent-control-cd/*'
agent-control-deployment:
  - changed-files:
      - any-glob-to-any-file: 'charts/agent-control-deployment/*'
mssql-otel:
  - changed-files:
      - any-glob-to-any-file: 'charts/mssql-otel/*'
mysql-otel:
  - changed-files:
      - any-glob-to-any-file: 'charts/mysql-otel/*'
newrelic-infra-operator:
  - changed-files:
      - any-glob-to-any-file: 'charts/newrelic-infra-operator/*'
newrelic-infrastructure:
  - changed-files:
      - any-glob-to-any-file: 'charts/newrelic-infrastructure/*'
newrelic-k8s-metrics-adapter:
  - changed-files:
      - any-glob-to-any-file: 'charts/newrelic-k8s-metrics-adapter/*'
newrelic-logging:
  - changed-files:
      - any-glob-to-any-file: 'charts/newrelic-logging/*'
newrelic-pixie:
  - changed-files:
      - any-glob-to-any-file: 'charts/newrelic-pixie/*'
nr-ebpf-agent:
  - changed-files:
      - any-glob-to-any-file: 'charts/nr-ebpf-agent/*'
nr-k8s-otel-collector:
  - changed-files:
      - any-glob-to-any-file: 'charts/nr-k8s-otel-collector/*'
nri-bundle:
  - changed-files:
      - any-glob-to-any-file: 'charts/nri-bundle/*'
nri-bundle-legacy:
  - changed-files:
      - any-glob-to-any-file: 'charts/nri-bundle-legacy/*'
nri-kube-events:
  - changed-files:
      - any-glob-to-any-file: 'charts/nri-kube-events/*'
nri-metadata-injection:
  - changed-files:
      - any-glob-to-any-file: 'charts/nri-metadata-injection/*'
nri-prometheus:
  - changed-files:
      - any-glob-to-any-file: 'charts/nri-prometheus/*'
nri-statsd:
  - changed-files:
      - any-glob-to-any-file: 'charts/nri-statsd/*'
oracle-otel:
  - changed-files:
      - any-glob-to-any-file: 'charts/oracle-otel/*'
pipeline-control-gateway:
  - changed-files:
      - any-glob-to-any-file: 'charts/pipeline-control-gateway/*'
postgresql-otel:
  - changed-files:
      - any-glob-to-any-file: 'charts/postgresql-otel/*'
synthetics-job-manager:
  - changed-files:
      - any-glob-to-any-file: 'charts/synthetics-job-manager/*'
synthetics-minion:
  - changed-files:
      - any-glob-to-any-file: 'charts/synthetics-minion/*'
common-library:
  - changed-files:
      - any-glob-to-any-file: 'library/common-library/*'