# Chart to Label mapping for Autolabeler
autolabeler:
  - label: 'agent-control-bootstrap'
    files:
      - 'charts/agent-control-bootstrap/*'
  - label: 'agent-control-cd'
    files:
      - 'charts/agent-control-cd/*'
  - label: 'agent-control-deployment'
    files:
      - 'charts/agent-control-deployment/*'
  - label: 'mssql-otel'
    files:
      - 'charts/mssql-otel/*'
  - label: 'mysql-otel'
    files:
      - 'charts/mysql-otel/*'
  - label: 'newrelic-infra-operator'
    files:
      - 'charts/newrelic-infra-operator/*'
  - label: 'newrelic-infrastructure'
    files:
      - 'charts/newrelic-infrastructure/*'
  - label: 'newrelic-k8s-metrics-adapter'
    files:
      - 'charts/newrelic-k8s-metrics-adapter/*'
  - label: 'newrelic-logging'
    files:
      - 'charts/newrelic-logging/*'
  - label: 'newrelic-pixie'
    files:
      - 'charts/newrelic-pixie/*'
  - label: 'nr-ebpf-agent'
    files:
      - 'charts/nr-ebpf-agent/*'
  - label: 'nr-k8s-otel-collector'
    files:
      - 'charts/nr-k8s-otel-collector/*'
  - label: 'nri-bundle'
    files:
      - 'charts/nri-bundle/*'
  - label: 'nri-bundle-legacy'
    files:
      - 'charts/nri-bundle-legacy/*'
  - label: 'nri-kube-events'
    files:
      - 'charts/nri-kube-events/*'
  - label: 'nri-metadata-injection'
    files:
      - 'charts/nri-metadata-injection/*'
  - label: 'nri-prometheus'
    files:
      - 'charts/nri-prometheus/*'
  - label: 'nri-statsd'
    files:
      - 'charts/nri-statsd/*'
  - label: 'oracle-otel'
    files:
      - 'charts/oracle-otel/*'
  - label: 'pipeline-control-gateway'
    files:
      - 'charts/pipeline-control-gateway/*'
  - label: 'postgresql-otel'
    files:
      - 'charts/postgresql-otel/*'
  - label: 'synthetics-job-manager'
    files:
      - 'charts/synthetics-job-manager/*'
  - label: 'synthetics-minion'
    files:
      - 'charts/synthetics-minion/*'
  - label: 'common-library'
    files:
      - 'library/common-library/*'
