# Auto Labeler configuration
autolabeler:
  - label: 'release/breaking'
    title:
      - '/!:/'
  - label: 'release/feature'
    title:
      - '/^feat/i'
  - label: 'release/fix'
    title:
      - '/^fix/i'
  - label: 'release/other'
    title:
      - '/^(build|chore|ci|docs|perf|refactor|revert|style|test)/i'

# Release Drafter configuration
#name-template: 'v$RESOLVED_VERSION 🌈'
#tag-template: 'v$RESOLVED_VERSION'
categories:
  - type: 'pre-include'
    when:
      - label: 'nr-k8s-otel-collector'
  - type: 'pre-exclude'
    when:
      - labels:
          - 'release/skip'
  - title: '💥 Breaking Changes'
    semver-increment: major
    when:
      - labels:
          - 'release/breaking'
  - title: '🚀 Features'
    semver-increment: minor
    when:
      - labels:
          - 'release/feature'
  - title: '🐛 Bug Fixes'
    when:
      - labels: 
          - 'release/fix'
  - title: '📝 Other'
    when:
      - labels:
          - 'release/other'

change-template: '- $TITLE (#$NUMBER) $AUTHORS'
change-title-escapes: '\<*_&'
replacers:
  # Remove conventional commit prefix
  - search: '/^- [a-zA-Z]+(\([a-zA-Z]+\))?!?:\s*/gm'
    replace: '- '
  # Uppercase the first letter of each changelog entry
  - search: '/- ([a-z])/g'
    replace: '- \u$1'

template: |
  $CHANGES
