# Auto Labeler configuration
#autolabeler:
#  - label: 'release/breaking'
#    title:
#      - '/!:/'
#  - label: 'release/feature'
#    title:
#      - '/^feat/i'
#  - label: 'release/fix'
#    title:
#      - '/^fix/i'
#  - label: 'release/other'
#    title:
#      - '/^(build|chore|ci|docs|perf|refactor|revert|style|test)/i'
autolabeler: []

# Release Drafter configuration
#name-template: 'v$RESOLVED_VERSION 🌈'
#tag-template: 'v$RESOLVED_VERSION'
categories:
  - type: 'pre-include'
    when:
      - label: 'nr-k8s-otel-collector'
  - type: 'pre-exclude'
    when:
      - label: 'release/skip'
  - title: '💥 Breaking Changes'
    semver-increment: major
    when:
      - conventional:
          type: 'feat'
          breaking: true
  - title: '🚀 Features'
    semver-increment: minor
    when:
      - conventional:
          type: 'feat'
  - title: '🐛 Bug Fixes'
    when:
      - conventional:
          type: 'fix'
  - title: '📝 Other'
    when:
      - conventional:
          type: 'build'

change-template: '- $TITLE (#$NUMBER) $AUTHORS'
change-title-escapes: '\<*_&'
replacers:
#  # Remove conventional commit prefix
#  - search: '/^- [a-zA-Z]+(\([a-zA-Z]+\))?!?:\s*/gm'
#    replace: '- '
  # Uppercase the first letter of each changelog entry
  - search: '/- ([a-z])/g'
    replace: '- \u$1'

template: |
  ## Changes

  $CHANGES