{{- include "oracle-otel.validate.oracle" . -}}
{{- if not .Values.oracle.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oracle-otel.credentials.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oracle-otel.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.oracle.username | b64enc }}
  password: {{ .Values.oracle.password | b64enc }}
{{- end }}
