apiVersion: v2
name: common-library
description: Provides helpers to provide consistency on all the charts

type: library
version: 2.3.5

keywords:
  - newrelic
  - chart-library

maintainers:
  - name: danielstokes
    url: https://github.com/danielstokes
  - name: dbudziwojskiNR
    url: https://github.com/dbudziwojskiNR
  - name: NRhzhao
    url: https://github.com/NRhzhao
  - name: Philip-R-Beckwith
    url: https://github.com/Philip-R-Beckwith
  - name: sachin-shankar
    url: https://github.com/sachin-shankar
  - name: TmNguyen12
    url: https://github.com/TmNguyen12
