{{- $deploymentWatcher := and (not .Values.daemonset.enabled) .Values.deployment.customConfigMap .Values.deployment.configWatcher.enabled }}
{{- $daemonsetWatcher := and .Values.daemonset.enabled .Values.daemonset.customConfigMap .Values.daemonset.configWatcher.enabled }}
{{- if and (include "newrelic.common.serviceAccount.create" .) (or $deploymentWatcher $daemonsetWatcher) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "newrelic.common.naming.fullname" . }}-config-watcher
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
rules:
  # Allow watching and getting the ConfigMap
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames:
      {{- if $deploymentWatcher }}
      - "{{ .Values.deployment.customConfigMap }}"
      {{- end }}
      {{- if $daemonsetWatcher }}
      - "{{ .Values.daemonset.customConfigMap }}"
      {{- end }}
    verbs: ["get", "watch"]
  # Allow deleting the pod to trigger restart
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete"]
{{- end -}}
