WHENEVER SQLERROR CONTINUE
DECLARE
  user_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO user_count FROM dba_users WHERE username = UPPER('&monitor_user');
  IF user_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER &monitor_user IDENTIFIED BY "&monitor_password"';
  END IF;
END;
/
WHENEVER SQLERROR EXIT SQL.SQLCODE

GRANT CREATE SESSION TO &monitor_user;
GRANT SELECT ON SYS.V_$INSTANCE TO &monitor_user;
GRANT SELECT ON SYS.V_$DATABASE TO &monitor_user;
GRANT SELECT ON SYS.V_$CONTAINERS TO &monitor_user;
GRANT SELECT ON SYS.V_$DATAFILE TO &monitor_user;
GRANT SELECT ON SYS.V_$PDBS TO &monitor_user;
GRANT SELECT ON SYS.V_$SYSSTAT TO &monitor_user;
GRANT SELECT ON SYS.V_$SYSMETRIC TO &monitor_user;
GRANT SELECT ON SYS.V_$SESSION TO &monitor_user;
GRANT SELECT ON SYS.V_$RESOURCE_LIMIT TO &monitor_user;
GRANT SELECT ON SYS.V_$OSSTAT TO &monitor_user;
GRANT SELECT ON SYS.V_$SGAINFO TO &monitor_user;
GRANT SELECT ON SYS.V_$ROWCACHE TO &monitor_user;
GRANT SELECT ON SYS.V_$PARAMETER TO &monitor_user;
GRANT SELECT ON SYS.DBA_TABLESPACE_USAGE_METRICS TO &monitor_user;
GRANT SELECT ON SYS.DBA_TABLESPACES TO &monitor_user;
GRANT SELECT ON SYS.DBA_DATA_FILES TO &monitor_user;
GRANT SELECT ON SYS.DBA_FREE_SPACE TO &monitor_user;
GRANT SELECT ON SYS.DBA_RECYCLEBIN TO &monitor_user;
GRANT SELECT ON SYS.V_$SQL TO &monitor_user;
GRANT SELECT ON SYS.V_$SQL_PLAN_STATISTICS_ALL TO &monitor_user;
GRANT SELECT ON SYS.V_$LOCK TO &monitor_user;
GRANT SELECT ON SYS.V_$SESSION_EVENT TO &monitor_user;
GRANT SELECT ON SYS.DBA_PROCEDURES TO &monitor_user;
GRANT SELECT ON SYS.DBA_OBJECTS TO &monitor_user;
EXIT;
