WHENEVER SQLERROR CONTINUE
DECLARE
  user_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO user_count FROM dba_users WHERE username = UPPER('&monitor_user');
  IF user_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER &monitor_user IDENTIFIED BY "&monitor_password"';
  END IF;
END;
/
WHENEVER SQLERROR EXIT SQL.SQLCODE

GRANT CREATE SESSION TO &monitor_user;
GRANT SELECT ON V_$INSTANCE TO &monitor_user;
GRANT SELECT ON V_$DATABASE TO &monitor_user;
GRANT SELECT ON V_$DATAFILE TO &monitor_user;
GRANT SELECT ON V_$SYSSTAT TO &monitor_user;
GRANT SELECT ON V_$SYSMETRIC TO &monitor_user;
GRANT SELECT ON V_$SESSION TO &monitor_user;
GRANT SELECT ON V_$RESOURCE_LIMIT TO &monitor_user;
GRANT SELECT ON V_$OSSTAT TO &monitor_user;
GRANT SELECT ON V_$SGAINFO TO &monitor_user;
GRANT SELECT ON V_$ROWCACHE TO &monitor_user;
GRANT SELECT ON V_$PARAMETER TO &monitor_user;
GRANT SELECT ON DBA_TABLESPACES TO &monitor_user;
GRANT SELECT ON DBA_DATA_FILES TO &monitor_user;
GRANT SELECT ON DBA_FREE_SPACE TO &monitor_user;
GRANT SELECT ON DBA_RECYCLEBIN TO &monitor_user;
GRANT SELECT ON V_$SQL TO &monitor_user;
GRANT SELECT ON V_$SQL_PLAN TO &monitor_user;
GRANT SELECT ON V_$LOCK TO &monitor_user;
GRANT SELECT ON V_$SESSION_EVENT TO &monitor_user;
GRANT SELECT ON DBA_PROCEDURES TO &monitor_user;
GRANT SELECT ON DBA_OBJECTS TO &monitor_user;
EXIT;
