# Documentation: https://newrelic.atlassian.net/wiki/spaces/INST/pages/4609638833/CDD+Metadata+to+be+stored
configurationDefinitions:
  - platform: KUBERNETESCLUSTER
    description: agent control configuration
    type: agent-control-config
    version: 1.0.0
