{{- include "postgresql-otel.validate.postgresql" . -}}
{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-otel.credentials.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql-otel.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgresql.username | b64enc }}
  password: {{ .Values.postgresql.password | b64enc }}
{{- end }}
