{{- include "mysql-otel.validate.mysql" . -}}
{{- if not .Values.mysql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-otel.credentials.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql-otel.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.mysql.username | b64enc }}
  password: {{ .Values.mysql.password | b64enc }}
{{- end }}
