# This is a dummy CM to test the resolve template
# and give examples on how to use it
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "newrelic.common.naming.fullname" . }}-examples-cm-resolve
  namespace: {{ .Release.Namespace }}
data:
  {{/* Using lookup With Default  */}}
  custom: {{ include "newrelic.common.resolve" (dict "ctx" . "key" "custom"  "default" "myDefaultData") -}}

  {{/* Look up only will return nothing if value not found */}}
  proxy: {{ include "newrelic.common.resolve" (dict "ctx" . "key" "proxy") -}}

  {{/* Example of using lookup with custom logic to set default */}}
  endpoint: {{ include "newrelic.common.resolve" (dict "ctx" . "key" "endpoint") | default "inline-default" -}}

  {{/* Example of using lookup test with a nested two-level path */}}
  nested_two_deep: {{ include "newrelic.common.resolve" (dict "ctx" . "key" "nested.value") -}}

  {{/* Example of using lookup test with a nested three-level path */}}
  nested_three_deep: {{ include "newrelic.common.resolve" (dict "ctx" . "key" "nested.secondLevel.value") -}}

  {{/* Example of using lookup with default with a nested path */}}
  nested_two_deep_with_default: {{ include "newrelic.common.resolve" (dict "ctx" . "key" "nested.value" "default" "defaultNestedValue") -}}

  {{/* Example of looking up a nested path that doesn't exist... (Test that this doesn't cause errors) */}}
  nested_value_DNE: {{ include "newrelic.common.resolve" (dict "ctx" . "key" "nested.blah.value.DNE") -}}
