configurationDefinitions:
  - platform: KUBERNETESCLUSTER
    type: AgentConfig
    version: 1.0.0
    format: yml
    bindings:
      - type: CONFIGURES
        targetType: AGENT
        target: NRDOT
        versions:
          - ">=0.10.2"
