.PHONY: generate-examples
install-helm-dependencies:
	echo 'Installing Helm Dependencies nr-k8s-otel-collector-> prometheus-community...'; \
	helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

