apiVersion: v1
kind: Secret
metadata:
  name: ac-deployment-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # Encode your values in base64
  agent-control-deployment.yaml: {{ (index .Values "agent-control-deployment") | toYaml | b64enc }}
  global.yaml: {{ .Values.global | toYaml | b64enc }}