apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name}}-deployment
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  agent-control-deployment.yaml: {{ (index .Values "agent-control-deployment") | toYaml | b64enc }}
  global.yaml: {{ .Values.global | toYaml | b64enc }}