# Default-install E2E values.
# licenseKey and cluster are injected via `--set global.*` in test-specs.yml.
# Left intentionally minimal so this scenario exercises the chart's defaults.
# Additional scenarios (namespace filtering, multi-line, lowDataMode) will add
# their own values files alongside this one.
