{{- include "mssql-otel.validate.mssql" . -}}
{{- if not .Values.mssql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mssql-otel.credentials.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mssql-otel.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.mssql.username | b64enc }}
  password: {{ .Values.mssql.password | b64enc }}
{{- end }}
