configurationDefinitions:
  - platform: KUBERNETESCLUSTER
    type: AgentConfig
    version: 1.0.0
    format: yml
    bindings:
      - type: CONFIGURES
        targetType: AGENT
        target: PipelineControlGateway
        versions:
          - ">1.0.0"
