name: Label PR
on:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]

permissions:
  contents: read

jobs:
  label-charts:
    name: Label PR with changed charts
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Remove fallback label in preparation for labeler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr edit "$PR_NUMBER" --remove-label "triage/needs-chart"

      - name: Run labeler for changed charts
        id: chart-labeler
        uses: actions/labeler@v7
        with:
          configuration-path: '.github/chart-labels.yml'
          sync-labels: 'true'

      - name: Apply fallback label
        env:
          LABELS: ${{ steps.chart-labeler.outputs.all-labels }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [ -z "$LABELS" ]; then
            echo "No labels found. Applying fallback label..."
            gh pr edit "$PR_NUMBER" --add-label "triage/needs-chart"
          else
            echo "PR already labeled correctly."
          fi
