name: Validate PR
on:
  pull_request

permissions:
  contents: read

jobs:
  label-charts:
    name: Label PR with changed charts
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      changed-charts: ${{ steps.chart-autolabeler.outputs.labels }}
    steps:
      - name: Remove labels in preparation for Autolabeler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # Fetch all existing labels, join them by commas, and pass them to the remove command
          LABELS=$(gh pr view "$PR_NUMBER" --json labels --jq '[.labels[].name] | join(",")')
          
          if [ -n "$LABELS" ]; then
            gh pr edit "$PR_NUMBER" --remove-label "$LABELS"
            echo "Successfully removed labels: $LABELS"
          else
            echo "No labels found to remove."
          fi

      - name: Run Autolabeler for changed charts
        id: chart-autolabeler
        uses: release-drafter/release-drafter/autolabeler@v7
        with:
          config-name: 'chart-autolabeler-config.yml'

      - name: Apply fallback label
        env:
          LABELS: ${{ steps.chart-autolabeler.outputs.labels }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [ -z "$LABELS" ]; then
            echo "No labels found. Applying fallback label..."
            gh pr edit "$PR_NUMBER" --add-label "triage/needs-chart"
          else
            echo "PR already labeled correctly."
          fi
  label-change-type-k8s-otel:
    if: contains(needs.label-charts.outputs.changed-charts, 'nr-k8s-otel-collector')
    name: Label PR with change type
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    needs: [ label-charts ]
    steps:
      - name: Run Autolabeler for change type
        uses: release-drafter/release-drafter/autolabeler@v7
        with:
          config-name: 'nr-k8s-otel-collector-release-drafter.yml'
      - name: Verify PR has a matched release category
        id: verify-release-category
        uses: release-drafter/release-drafter@v7
#        uses: release-drafter/release-drafter/check-pr@f259c0ada5376557cd49e74487398301fab5287a
        with:
          config-name: 'nr-k8s-otel-collector-release-drafter.yml'
      - name: Print Changelog Category
        run: |
          echo "Changelog Category: ${{ steps.verify-release-category.outputs.resolved_version }}"
          echo "Changelog Category: ${{ steps.verify-release-category.outputs.body }}"
