name: Test Renovate configuration

on: pull_request

jobs:
  renovate-config-validator:
    name: Renovate config validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Test that the config is valid
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/.github/renovate.json5:/usr/src/app/renovate.json5" \
            ghcr.io/renovatebot/renovate:latest \
            renovate-config-validator renovate.json5
